import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback, useState } from "react";
import { useRouter } from "next/router";
import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { signUpSchema, ISignUp } from "../common/validation/auth";
import { trpc } from "../common/trpc";
import { TRPCClientError } from "@trpc/client";
import ErrorMessage from "../components/messages/error";
import SignUpSuccess from "../components/messages/signUpSuccess";
import signUpSuccess from "../components/messages/signUpSuccess";

const VerifyRequest: NextPage = () => {
  const router = useRouter();

  const [errorMessage, setErrorMessage] = useState<any>(null);
  const [showSuccessModal, setShowSuccessModal] = useState(false);

  const { handleSubmit, control, reset } = useForm<ISignUp>({
    defaultValues: {
      name: "",
      email: "",
      // password: "",
    },
    resolver: zodResolver(signUpSchema),
  });

  const { mutateAsync } = trpc.signup.useMutation();

  const onSubmit = useCallback(
    async (data: ISignUp) => {
      try {
        const result = await mutateAsync(data);
        if (result.status === 201) {
          reset();

          setShowSuccessModal(true);
        }
      } catch (err) {
        if (err instanceof TRPCClientError) {
          console.log(err);
          setErrorMessage(err.message || "An error occurred");
        }
        console.error(err);
      }
    },
    [mutateAsync, router, reset]
  );

  return (
    <div>
      <Head>
        <title>Next App - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {errorMessage && <ErrorMessage message={errorMessage} />}
        <form
          className="flex items-center justify-center h-screen w-full"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="card w-96 bg-base-100 shadow-xl">
            <div className="card-body">
              <h2 className="card-title">Check you mail</h2>
              <h3>A sign in link has been sent to your email address.</h3>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
};

export default VerifyRequest;
